artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/pratim808/Mushroom_clsassification/raw/main/mushrooms.zip
  local_data_file: artifacts/data_ingestion/mushrooms.zip
  unzip_dir: artifacts/data_ingestion
